// Every spoken instruction. `gen-audio` renders these with ElevenLabs; missing generated prompts can use runtime TTS.
export const PROMPTS = {
  welcome: 'Hi! Let’s read.',
  new_sound: 'Here is a new sound.',
  this_sound_is: 'This sound is',
  my_turn: 'My turn.',
  together: 'Say it with me.',
  your_turn: 'Your turn.',
  tap_sound: 'Tap the sound',
  say_sound: 'What sound?',
  hold_it: 'Hold the sound. Keep your voice on, and the kite flies!',
  glide: 'Keep your voice on. Slide through the sounds!',
  say_fast: 'Say it fast!',
  read_match: 'Read the word. Tap the picture.',
  which_word: 'Tap the word',
  build_it: 'Build the word',
  alien: 'This is a silly alien name. Sound it out!',
  sentence: 'Read the sentence. Tap each word as you read it.',
  ear_listen: 'Listen. What word is it?',
  ear_rhyme: 'Which one rhymes with',
  ear_first: 'Which one starts with',
  ear_last: 'Which one ends with',
  ear_middle: 'Which one has',
  ear_middle_end: 'in the middle?',
  segment_word: 'Say each sound in',
  meaning: 'Which picture was in what you read?',
  yes_1: 'Yes!',
  yes_2: 'That’s it.',
  yes_3: 'You got it.',
  again: 'Let’s try that one again.',
  kite_fell: 'The kite needs your voice to stay on. Try again!',
  checkout: 'Let’s show what you know.',
  cold: 'Let’s remember yesterday.',
  level_done: 'You finished a level!',
  story_time: 'Go find someone. It’s story time! Read it to them.',
  story_tap: 'When you have read it, tap the big green button!',
  all_done: 'All done for today. See you tomorrow!',
  rest: 'Your brain worked hard. Let’s rest.',
  tap_dogfish: 'Tap dogfish.',
  tap_fishdog: 'Tap fishdog.',
  ready_intro: 'Let’s play a little game.',
  heart_word: 'This is a heart word. We learn it by heart. It says',
  heart_read: 'Read this heart word.',
  story: 'Read the story. Tap each word as you read it.',
  book_ready: 'You can read a new book!',
  watch_me: 'Watch me first.',
  say_fast_game: "Let's play say it fast! Listen.",
  which_picture: 'Which picture is it?',
  it_is: "It's",
  sound_says: 'This letter says',
  like_in: 'like in',
  find_sound: 'Find the letter that says',
  rhyme_teach: 'These words rhyme. They sound the same at the end.',
  rhyme_ask: 'Do these words rhyme?',
  rhyme_yes: 'Yes! They rhyme.',
  rhyme_no: "No, they don't rhyme.",
  track_game: 'Help the kite fly. Tap the dots, one by one.',
  basics_done: 'You learned a new sound today!',
} as const;

export type PromptId = keyof typeof PROMPTS;
